[package]
name = "ssize"
version = "0.1.0"
edition = "2021"

[dependencies]
stack-sizes = "0.5.0"
rustc-demangle = "0.1.23"
cargo-project = "0.3.0"
anyhow = "1.0.74"
rustc_version = "0.4.0"
clap = { version = "4.1.6", features = ["derive"] }
env_logger = "0.10.0"
